# 接続先設定ファイル
# 踏み台サーバはリスト形式で定義（上から順に経由する）

bastions:
  - name: bastion-1
    host: 192.168.3.23
    port: 23
    protocol: telnet
    username: sysope
    password: "P!ssw0rd1234"

devices:
  - name: vmx1
    host: 172.20.20.2
    port: 22
    protocol: ssh
    vendor: juniper
    username: admin
    password: "admin@123"
